### ISSUE TITLE
Dynamic Framework/Modular

### ISSUE THREAD

**Issue by mm188200** [jshier/GigyaSDK#12]
Not sure if anyone here will have insight into this, but was wondering if there was a status on getting a dynamic library or a modular framework for the Gigya SDK.  We are using swift and are able to use the current cocoapod directly, but when integrating into our own Framework, we are unable to properly build and reference the Gigya SDK within the framework (from the various things I have tried, and it seems pretty clear from documentation it may not be possible until the Gigya SDK is updated).  

Errors depending on config:
[!] The 'Pods-CoreAppTemplate' target has transitive dependencies that include static binaries: (/Users/michaelmorris/NewOUSPlatform/ios/Gigya-Modular/Frameworks/GigyaSDK.framework)

or when adding a header to umbrella header for modules:
include of non-modular header inside framework module

I will also try to float this through our contacts at Gigya, but thought I would give it a shot here first (couldnt find any way to contact devs on the Gigya website).  Any help would be much appreciated, or if you have any questions let me know.  Thanks

**Comment by jshier** [comment]
Unfortunately that's entirely up to Gigya. I suggest you reach out to them and see if they'll share any plans they have in this area. A separate possibility would be trying to get the source to the SDK, available from Gigya, to build directly yourself. That way you can have it dynamically available and not get that CocoaPods error. I've tried before and it's not easy, but I no longer have the time or interest in doing it (I'm no longer actively using Gigya).

**Comment by mm188200** [comment]
figured that might be the case, appreciate the response, will reach out to them.
